class GeneralInfo:
    BMW_CATALOG = "a[href*='/bmw/enUS/select']"
    VIN_INPUT = "#vin"
    DISMISS_ADBLOCK = "span.ggmtgz:has-text('×')" 
    FIRST_SEARCH_BUTTON = "input[type='submit'][value='Search']"
    BROWSE_PARTS_BUTTON = "input[type='submit'][value='        Browse Parts        ']"
    ENGINE = "a:has(div:has-text('ENGINE'))"
    TECHNICAL_LITERATURE = "a:has(div:has-text('TECHNICAL LITERATURE'))"
    RADIATOR = "a:has(div:has-text('RADIATOR'))"
    CLUTCH = "a:has(div:has-text('CLUTCH'))"
    FUEL_SUPPLY = "a:has(div:has-text('FUEL SUPPLY'))"
    EXHAUST_SYSTEM = "a:has(div:has-text('EXHAUST SYSTEM'))"
    DRIVE_SHAFT = "a:has(div:has-text('DRIVE SHAFT'))"
    GEARSHIFT = "a:has(div:has-text('GEARSHIFT'))"
    STEERING = "a:has(div:has-text('STEERING'))"
    SUSPENSION = "a:has(div:has-text('ENGINE AND TRANSMISSION SUSPENSION'))"
    BRAKES = "a:has(div:has-text('BRAKES'))"
    WHEELS = "a:has(div:has-text('WHEELS'))"
    RETROFITTING = "a:has(div:has-text('RETROFITTING'))"
    ENGINE_ELEC_SYSTEM = "a:has(div:has-text('ENGINE ELECTRICAL SYSTEM'))"
    FUEL_PREP = "a:has(div:has-text('FUEL PREPARATION'))"
    AUTOMATIC_TRANSMISSION = "a:has(div:has-text('AUTOMATIC TRANSMISSION'))"
    MANUAL_TRANSMISSION = "a:has(div:has-text('MANUAL TRANSMISSION'))"
    TRIM = "a:has(div:has-text('TRIM'))"
    PEDALS = "a:has(div:has-text('PEDALS'))"
    BODYWORK = "a:has(div:has-text('BODYWORK'))"
    VEHICLE_TRIM = "a:has(div:has-text('VEHICLE TRIM'))"
    SEATS = "a:has(div:has-text('SEATS'))"
    SLIDING_ROOF = "a:has(div:has-text('SLIDING ROOF'))"
    INSTRUMENTS = "a:has(div:has-text('INSTRUMENTS'))"
    LIGHTING = "a:has(div:has-text('LIGHTING'))"
    HEATER_AC = "a:has(div:has-text('HEATER AND AIR CONDITIONING'))"
    AUDIO_NAV = "a:has(div:has-text('AUDIO, NAVIGATION'))"
    DISTANCE_SYSTEMS = "a:has(div:has-text('DISTANCE SYSTEMS'))"
    EQU_PARTS = "a:has(div:has-text('EQUIPMENT PARTS'))"
    RESTRAINT_SYSTEM = "a:has(div:has-text('RESTRAINT SYSTEM'))"
    AUX_MATERIALS = "a:has(div:has-text('AUXILIARY MATERIALS'))"
    COMM_SYSTEMS = "a:has(div:has-text('COMMUNICATION SYSTEMS'))"
    VALUE_PARTS = "a:has(div:has-text('VALUE PARTS'))"
    QUICK_SERVICE = "a:has(div:has-text('SERVICE AND SCOPE OF REPAIR WORK'))"