services:
  - type: web
    name: superetka-scraper
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /
envVars:
  - key: PUPPETEER_EXECUTABLE_PATH
    value: "/usr/bin/chromium-browser"
